// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_-tXVHwlKJtKPrDt5j620v11mUkS8zRc',
    appId: '1:749962494199:web:f64ae3676767fad93b13f2',
    messagingSenderId: '749962494199',
    projectId: 'bookingdoctor-6a5a1',
    authDomain: 'bookingdoctor-6a5a1.firebaseapp.com',
    storageBucket: 'bookingdoctor-6a5a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZWAJS9FhebzxSUNdbAZUWXByQylVV_24',
    appId: '1:749962494199:android:34af9b3ea21c0d9f3b13f2',
    messagingSenderId: '749962494199',
    projectId: 'bookingdoctor-6a5a1',
    storageBucket: 'bookingdoctor-6a5a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzJOguBzvqHfIGr_WXeB-Hqn8EXtGAnXE',
    appId: '1:749962494199:ios:53c393c15396e7793b13f2',
    messagingSenderId: '749962494199',
    projectId: 'bookingdoctor-6a5a1',
    storageBucket: 'bookingdoctor-6a5a1.appspot.com',
    iosClientId: '749962494199-4hp9sqgopbu44ilahuqgv1e05ivd7bcl.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingDoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzJOguBzvqHfIGr_WXeB-Hqn8EXtGAnXE',
    appId: '1:749962494199:ios:75594402d997d4613b13f2',
    messagingSenderId: '749962494199',
    projectId: 'bookingdoctor-6a5a1',
    storageBucket: 'bookingdoctor-6a5a1.appspot.com',
    iosClientId: '749962494199-r193407nnmt979h717hnkrlrrk3eq33l.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingDoctor.RunnerTests',
  );
}
